### ISSUE TITLE
Recordings master issue

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2020#7]
- [x] Welcome Address - Sabra
- [x] Keynote - Nii Okai
- [x] FOSS Overview / Use Cases - Enock
- [ ] ~~Nyansapo OS - Rexford~~
- [ ] ~~Open Hardware - Fafali~~
- [x] OpenStreetMap - Angela, OSM Ghana
- [ ] ~~Automation using Bots - Bright~~
- [x] Closing Remarks - Sabra
